//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyStyleClient.SalonServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalonServiceReference.SalonServiceSoap")]
    public interface SalonServiceSoap {
        
        // CODEGEN: Generating message contract since element name customerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookAppointment", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.BookAppointmentResponse BookAppointment(BookMyStyleClient.SalonServiceReference.BookAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.BookAppointmentResponse> BookAppointmentAsync(BookMyStyleClient.SalonServiceReference.BookAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name serviceType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableStaff", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponse GetAvailableStaff(BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponse> GetAvailableStaffAsync(BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest request);
        
        // CODEGEN: Generating message contract since element name customerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppointmentsByCustomer", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponse GetAppointmentsByCustomer(BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppointmentsByCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponse> GetAppointmentsByCustomerAsync(BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name bookingId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.CancelBookingResponse CancelBooking(BookMyStyleClient.SalonServiceReference.CancelBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.CancelBookingResponse> CancelBookingAsync(BookMyStyleClient.SalonServiceReference.CancelBookingRequest request);
        
        // CODEGEN: Generating message contract since element name customerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePreferences", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.SavePreferencesResponse SavePreferences(BookMyStyleClient.SalonServiceReference.SavePreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePreferences", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.SavePreferencesResponse> SavePreferencesAsync(BookMyStyleClient.SalonServiceReference.SavePreferencesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllBookingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBookings", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.GetAllBookingsResponse GetAllBookings(BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAllBookingsResponse> GetAllBookingsAsync(BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPreferencesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPreferences", ReplyAction="*")]
        BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponse GetAllPreferences(BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPreferences", ReplyAction="*")]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponse> GetAllPreferencesAsync(BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookAppointment", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.BookAppointmentRequestBody Body;
        
        public BookAppointmentRequest() {
        }
        
        public BookAppointmentRequest(BookMyStyleClient.SalonServiceReference.BookAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string serviceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dateTime;
        
        public BookAppointmentRequestBody() {
        }
        
        public BookAppointmentRequestBody(string customerName, string serviceType, string dateTime) {
            this.customerName = customerName;
            this.serviceType = serviceType;
            this.dateTime = dateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.BookAppointmentResponseBody Body;
        
        public BookAppointmentResponse() {
        }
        
        public BookAppointmentResponse(BookMyStyleClient.SalonServiceReference.BookAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookAppointmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookAppointmentResult;
        
        public BookAppointmentResponseBody() {
        }
        
        public BookAppointmentResponseBody(string BookAppointmentResult) {
            this.BookAppointmentResult = BookAppointmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableStaff", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequestBody Body;
        
        public GetAvailableStaffRequest() {
        }
        
        public GetAvailableStaffRequest(BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serviceType;
        
        public GetAvailableStaffRequestBody() {
        }
        
        public GetAvailableStaffRequestBody(string serviceType) {
            this.serviceType = serviceType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponseBody Body;
        
        public GetAvailableStaffResponse() {
        }
        
        public GetAvailableStaffResponse(BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAvailableStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAvailableStaffResult;
        
        public GetAvailableStaffResponseBody() {
        }
        
        public GetAvailableStaffResponseBody(BookMyStyleClient.SalonServiceReference.ArrayOfString GetAvailableStaffResult) {
            this.GetAvailableStaffResult = GetAvailableStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppointmentsByCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppointmentsByCustomer", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequestBody Body;
        
        public GetAppointmentsByCustomerRequest() {
        }
        
        public GetAppointmentsByCustomerRequest(BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppointmentsByCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerName;
        
        public GetAppointmentsByCustomerRequestBody() {
        }
        
        public GetAppointmentsByCustomerRequestBody(string customerName) {
            this.customerName = customerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppointmentsByCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppointmentsByCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponseBody Body;
        
        public GetAppointmentsByCustomerResponse() {
        }
        
        public GetAppointmentsByCustomerResponse(BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppointmentsByCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAppointmentsByCustomerResult;
        
        public GetAppointmentsByCustomerResponseBody() {
        }
        
        public GetAppointmentsByCustomerResponseBody(BookMyStyleClient.SalonServiceReference.ArrayOfString GetAppointmentsByCustomerResult) {
            this.GetAppointmentsByCustomerResult = GetAppointmentsByCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelBooking", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.CancelBookingRequestBody Body;
        
        public CancelBookingRequest() {
        }
        
        public CancelBookingRequest(BookMyStyleClient.SalonServiceReference.CancelBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookingId;
        
        public CancelBookingRequestBody() {
        }
        
        public CancelBookingRequestBody(string bookingId) {
            this.bookingId = bookingId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.CancelBookingResponseBody Body;
        
        public CancelBookingResponse() {
        }
        
        public CancelBookingResponse(BookMyStyleClient.SalonServiceReference.CancelBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelBookingResult;
        
        public CancelBookingResponseBody() {
        }
        
        public CancelBookingResponseBody(string CancelBookingResult) {
            this.CancelBookingResult = CancelBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePreferencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePreferences", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.SavePreferencesRequestBody Body;
        
        public SavePreferencesRequest() {
        }
        
        public SavePreferencesRequest(BookMyStyleClient.SalonServiceReference.SavePreferencesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePreferencesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stylist;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string service;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string notification;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string notes;
        
        public SavePreferencesRequestBody() {
        }
        
        public SavePreferencesRequestBody(string customerName, string stylist, string service, string notification, string notes) {
            this.customerName = customerName;
            this.stylist = stylist;
            this.service = service;
            this.notification = notification;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePreferencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePreferencesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.SavePreferencesResponseBody Body;
        
        public SavePreferencesResponse() {
        }
        
        public SavePreferencesResponse(BookMyStyleClient.SalonServiceReference.SavePreferencesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePreferencesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SavePreferencesResult;
        
        public SavePreferencesResponseBody() {
        }
        
        public SavePreferencesResponseBody(string SavePreferencesResult) {
            this.SavePreferencesResult = SavePreferencesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookings", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAllBookingsRequestBody Body;
        
        public GetAllBookingsRequest() {
        }
        
        public GetAllBookingsRequest(BookMyStyleClient.SalonServiceReference.GetAllBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBookingsRequestBody {
        
        public GetAllBookingsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAllBookingsResponseBody Body;
        
        public GetAllBookingsResponse() {
        }
        
        public GetAllBookingsResponse(BookMyStyleClient.SalonServiceReference.GetAllBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAllBookingsResult;
        
        public GetAllBookingsResponseBody() {
        }
        
        public GetAllBookingsResponseBody(BookMyStyleClient.SalonServiceReference.ArrayOfString GetAllBookingsResult) {
            this.GetAllBookingsResult = GetAllBookingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPreferencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPreferences", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequestBody Body;
        
        public GetAllPreferencesRequest() {
        }
        
        public GetAllPreferencesRequest(BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPreferencesRequestBody {
        
        public GetAllPreferencesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPreferencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPreferencesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponseBody Body;
        
        public GetAllPreferencesResponse() {
        }
        
        public GetAllPreferencesResponse(BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPreferencesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAllPreferencesResult;
        
        public GetAllPreferencesResponseBody() {
        }
        
        public GetAllPreferencesResponseBody(BookMyStyleClient.SalonServiceReference.ArrayOfString GetAllPreferencesResult) {
            this.GetAllPreferencesResult = GetAllPreferencesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalonServiceSoapChannel : BookMyStyleClient.SalonServiceReference.SalonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalonServiceSoapClient : System.ServiceModel.ClientBase<BookMyStyleClient.SalonServiceReference.SalonServiceSoap>, BookMyStyleClient.SalonServiceReference.SalonServiceSoap {
        
        public SalonServiceSoapClient() {
        }
        
        public SalonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.BookAppointmentResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.BookAppointment(BookMyStyleClient.SalonServiceReference.BookAppointmentRequest request) {
            return base.Channel.BookAppointment(request);
        }
        
        public string BookAppointment(string customerName, string serviceType, string dateTime) {
            BookMyStyleClient.SalonServiceReference.BookAppointmentRequest inValue = new BookMyStyleClient.SalonServiceReference.BookAppointmentRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.BookAppointmentRequestBody();
            inValue.Body.customerName = customerName;
            inValue.Body.serviceType = serviceType;
            inValue.Body.dateTime = dateTime;
            BookMyStyleClient.SalonServiceReference.BookAppointmentResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).BookAppointment(inValue);
            return retVal.Body.BookAppointmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.BookAppointmentResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.BookAppointmentAsync(BookMyStyleClient.SalonServiceReference.BookAppointmentRequest request) {
            return base.Channel.BookAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.BookAppointmentResponse> BookAppointmentAsync(string customerName, string serviceType, string dateTime) {
            BookMyStyleClient.SalonServiceReference.BookAppointmentRequest inValue = new BookMyStyleClient.SalonServiceReference.BookAppointmentRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.BookAppointmentRequestBody();
            inValue.Body.customerName = customerName;
            inValue.Body.serviceType = serviceType;
            inValue.Body.dateTime = dateTime;
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).BookAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAvailableStaff(BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest request) {
            return base.Channel.GetAvailableStaff(request);
        }
        
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAvailableStaff(string serviceType) {
            BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequestBody();
            inValue.Body.serviceType = serviceType;
            BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAvailableStaff(inValue);
            return retVal.Body.GetAvailableStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAvailableStaffAsync(BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest request) {
            return base.Channel.GetAvailableStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAvailableStaffResponse> GetAvailableStaffAsync(string serviceType) {
            BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAvailableStaffRequestBody();
            inValue.Body.serviceType = serviceType;
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAvailableStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAppointmentsByCustomer(BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest request) {
            return base.Channel.GetAppointmentsByCustomer(request);
        }
        
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAppointmentsByCustomer(string customerName) {
            BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequestBody();
            inValue.Body.customerName = customerName;
            BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAppointmentsByCustomer(inValue);
            return retVal.Body.GetAppointmentsByCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAppointmentsByCustomerAsync(BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest request) {
            return base.Channel.GetAppointmentsByCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerResponse> GetAppointmentsByCustomerAsync(string customerName) {
            BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAppointmentsByCustomerRequestBody();
            inValue.Body.customerName = customerName;
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAppointmentsByCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.CancelBookingResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.CancelBooking(BookMyStyleClient.SalonServiceReference.CancelBookingRequest request) {
            return base.Channel.CancelBooking(request);
        }
        
        public string CancelBooking(string bookingId) {
            BookMyStyleClient.SalonServiceReference.CancelBookingRequest inValue = new BookMyStyleClient.SalonServiceReference.CancelBookingRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.CancelBookingRequestBody();
            inValue.Body.bookingId = bookingId;
            BookMyStyleClient.SalonServiceReference.CancelBookingResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).CancelBooking(inValue);
            return retVal.Body.CancelBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.CancelBookingResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.CancelBookingAsync(BookMyStyleClient.SalonServiceReference.CancelBookingRequest request) {
            return base.Channel.CancelBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.CancelBookingResponse> CancelBookingAsync(string bookingId) {
            BookMyStyleClient.SalonServiceReference.CancelBookingRequest inValue = new BookMyStyleClient.SalonServiceReference.CancelBookingRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.CancelBookingRequestBody();
            inValue.Body.bookingId = bookingId;
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).CancelBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.SavePreferencesResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.SavePreferences(BookMyStyleClient.SalonServiceReference.SavePreferencesRequest request) {
            return base.Channel.SavePreferences(request);
        }
        
        public string SavePreferences(string customerName, string stylist, string service, string notification, string notes) {
            BookMyStyleClient.SalonServiceReference.SavePreferencesRequest inValue = new BookMyStyleClient.SalonServiceReference.SavePreferencesRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.SavePreferencesRequestBody();
            inValue.Body.customerName = customerName;
            inValue.Body.stylist = stylist;
            inValue.Body.service = service;
            inValue.Body.notification = notification;
            inValue.Body.notes = notes;
            BookMyStyleClient.SalonServiceReference.SavePreferencesResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).SavePreferences(inValue);
            return retVal.Body.SavePreferencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.SavePreferencesResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.SavePreferencesAsync(BookMyStyleClient.SalonServiceReference.SavePreferencesRequest request) {
            return base.Channel.SavePreferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.SavePreferencesResponse> SavePreferencesAsync(string customerName, string stylist, string service, string notification, string notes) {
            BookMyStyleClient.SalonServiceReference.SavePreferencesRequest inValue = new BookMyStyleClient.SalonServiceReference.SavePreferencesRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.SavePreferencesRequestBody();
            inValue.Body.customerName = customerName;
            inValue.Body.stylist = stylist;
            inValue.Body.service = service;
            inValue.Body.notification = notification;
            inValue.Body.notes = notes;
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).SavePreferencesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.GetAllBookingsResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAllBookings(BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest request) {
            return base.Channel.GetAllBookings(request);
        }
        
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAllBookings() {
            BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAllBookingsRequestBody();
            BookMyStyleClient.SalonServiceReference.GetAllBookingsResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAllBookings(inValue);
            return retVal.Body.GetAllBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAllBookingsResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAllBookingsAsync(BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest request) {
            return base.Channel.GetAllBookingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAllBookingsResponse> GetAllBookingsAsync() {
            BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAllBookingsRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAllBookingsRequestBody();
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAllBookingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponse BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAllPreferences(BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest request) {
            return base.Channel.GetAllPreferences(request);
        }
        
        public BookMyStyleClient.SalonServiceReference.ArrayOfString GetAllPreferences() {
            BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequestBody();
            BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponse retVal = ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAllPreferences(inValue);
            return retVal.Body.GetAllPreferencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponse> BookMyStyleClient.SalonServiceReference.SalonServiceSoap.GetAllPreferencesAsync(BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest request) {
            return base.Channel.GetAllPreferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookMyStyleClient.SalonServiceReference.GetAllPreferencesResponse> GetAllPreferencesAsync() {
            BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest inValue = new BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequest();
            inValue.Body = new BookMyStyleClient.SalonServiceReference.GetAllPreferencesRequestBody();
            return ((BookMyStyleClient.SalonServiceReference.SalonServiceSoap)(this)).GetAllPreferencesAsync(inValue);
        }
    }
}
